quarkus:
  google:
    cloud:
      project-id: ${QUARKUS_GOOGLE_CLOUD_PROJECT_ID:active-bolt-478008-c9}
  http:
    port: 8081
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${DB_URL}
      max-size: 20  # Maximum number of connections in the pool
      min-size: 20   # Minimum number of idle connections maintained
      acquisition-timeout: 30s  # Wait up to 30s for a connection
      leak-detection-interval: 5M  # Detect and log connection leaks
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mybatis:
    map-underscore-to-camel-case: true
  native:
    resources:
      includes:
        - db/migration/**
#  log:
#    category:
#      # Apache Camel Google PubSub consumer
#      org.apache.camel.component.google.pubsub:
#        level: DEBUG
#      org.apache.camel.component.google.pubsub.GooglePubsubConsumer:
#        level: DEBUG
#      # Google Cloud Pub/Sub Java Subscriber
#      com.google.cloud.pubsub.v1.Subscriber:
#        level: DEBUG
#      # Google API client (GAX)
#      com.google.api.gax:
#        level: DEBUG
#      # gRPC transport (very verbose, enable only when needed)
#      io.grpc:
#        level: DEBUG
pubsub:
  subscription-id: ${SUBSCRIPTION_ID}
  pull-options: ${PULL_OPTIONS}
  subscriber:
    parallel-pull-count: ${PARALLEL_PULL_COUNT}
    executor-thread-count: ${EXECUTOR_THREAD_COUNT}

workers:
  persist-result:
    size: 10
